# Налаштування порту сервера
server.port=8080

# Дозволяємо перевизначати біни, якщо виникнуть конфлікти
spring.main.allow-bean-definition-overriding=true

# Вимикаємо автоматичний пошук бази даних через properties, 
# оскільки ми прописали exclude у головному класі Tpplab3Application.java